language: python
    - "3.2"
    - "3.4"
    - "3.5"
    - "3.6"
before_install:
    - sudo apt-get update -qq
    - sudo apt-get install -qq python3-pip python3-numpy python3-scipy python3-matplotlib python3-nose
    - sudo pip3 install codecov rednose nose coverage six toolz nose-parameterized codeclimate-test-reporter
cache: pip
script: nosetests3
dist: trusty
after_success:
    - codeclimate-test-reporter --token 71eb68ef3ba1f85d8e92407d03e43df51deb6f14a870ada23e8530a16d438eae
    - codecov --token=e3a3e622-b5b4-40a0-b0be-f427bbb23449
