language: python
    - "3.4"
    - "3.5"
before_install:
    - sudo apt-get update -qq
    - sudo apt-get install -qq python3-pip python3-numpy python3-scipy python3-matplotlib
    - sudo pip3 install codecov rednose nose coverage six toolz --upgrade
cache: pip
script: nosetests
after_success:
    codecov
