language: python
    - "3.4"
    - "3.5"
before_install:
    - sudo apt-get update -qq
    - sudo apt-get install -qq python3-pip python3-numpy python3-scipy
install:
    - pip3 install -r requirements.txt
    - pip3 install codecov
script: python3 setup.py install
after_success:
    codecov
